# Generated by Django 5.1.2 on 2024-11-23 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces.', regex='^[A-Za-z\\s]+$')])),
                ('loginid', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Login ID must contain only alphanumeric characters and underscores.', regex='^\\w+$')])),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long.', regex='^.{8,}$')])),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$')])),
                ('locality', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=250)),
                ('status', models.CharField(default='waiting', max_length=100)),
            ],
        ),
    ]
