# Generated by Django 4.2.16 on 2024-11-26 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='loginid',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Login ID must contain only letters', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile must start with 5, 6, 7, 8, or 9 and be 10 digits long', regex='^[6789][0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Password must contain at least one number, one uppercase, one lowercase letter, and at least 8 characters', regex='(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}')]),
        ),
    ]
