# Generated by Django 4.1.1 on 2025-03-15 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_userregistrationmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile must start with 5, 6, 7, 8, or 9 and be 10 digits long', regex='^[6789][0-9]{9}$')]),
        ),
    ]
